// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfd4Jy00CWv6wxR00ZAbnOtV05Ncl2Gv8',
    appId: '1:285877826911:web:bd87b0c17fb77ff24bb2ea',
    messagingSenderId: '285877826911',
    projectId: 'redblue-1614a',
    authDomain: 'redblue-1614a.firebaseapp.com',
    storageBucket: 'redblue-1614a.firebasestorage.app',
    measurementId: 'G-SG6L79KJ6B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmBq9wGoaRufSy9HjT7e1qag2HVts2Jtc',
    appId: '1:285877826911:android:bec374a30d82ac274bb2ea',
    messagingSenderId: '285877826911',
    projectId: 'redblue-1614a',
    storageBucket: 'redblue-1614a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIIMtPprKlobLMQfbUQMq7tbTVqqL58-c',
    appId: '1:285877826911:ios:ed4acb80e26c9be84bb2ea',
    messagingSenderId: '285877826911',
    projectId: 'redblue-1614a',
    storageBucket: 'redblue-1614a.firebasestorage.app',
    iosBundleId: 'com.redbluefx.redbluefxMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIIMtPprKlobLMQfbUQMq7tbTVqqL58-c',
    appId: '1:285877826911:ios:ed4acb80e26c9be84bb2ea',
    messagingSenderId: '285877826911',
    projectId: 'redblue-1614a',
    storageBucket: 'redblue-1614a.firebasestorage.app',
    iosBundleId: 'com.redbluefx.redbluefxMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfd4Jy00CWv6wxR00ZAbnOtV05Ncl2Gv8',
    appId: '1:285877826911:web:b27366aea9e7f5684bb2ea',
    messagingSenderId: '285877826911',
    projectId: 'redblue-1614a',
    authDomain: 'redblue-1614a.firebaseapp.com',
    storageBucket: 'redblue-1614a.firebasestorage.app',
    measurementId: 'G-EP0G3J317Y',
  );
}
